# Generated by Django 4.2.1 on 2023-06-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='pets', to='groups.group'),
            preserve_default=False,
        ),
    ]
