# Generated by Django 4.2.1 on 2023-06-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_trait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='trait',
            new_name='traits',
        ),
    ]
