# Generated by Django 4.2.1 on 2023-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_group'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='pet',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
